@SPT_API_HostAddress = http://localhost:5119

GET {{SPT_API_HostAddress}}/spt/StudentModel
Accept: application/json

###  
GET {{SPT_API_HostAddress}}/spt/StudentModel/search?FirstName=David&LastName=Oyem
Accept: application/json

###
POST {{SPT_API_HostAddress}}/spt/StudentModel/create
Content-Type: application/json
{
  "firstName": "David",
  "lastName": "Oyem",
  "department": "Petroleum Engineering",
  "level": "400",
  "studentPassword":"Vision@cu",
  "uniqueUserId": "m"
}
###
DELETE {{SPT_API_HostAddress}}/spt/StudentModel/delete
Content-Type: application/json
{
  "_firstName": "David",
  "_lastName": "Oyem",
  "_studentUsername": "daoyec",
  "_studentPassword": "Vision@cu"
}
###
PATCH {{SPT_API_HostAddress}}/spt/StudentModel/edit/daoy42
Content-Type: application/json
{
    "email": "oyemdavid12@gmail.com"
}
###
POST {{SPT_API_HostAddress}}/spt/StudentModel/login
Content-Type: application/json
{
    "_UserName": "daoyd6",
    "_Password": "Vision@cu"
}
###
GET {{SPT_API_HostAddress}}/spt/c/CourseModel/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjFkZTJlZDY5IiwibmJmIjoxNzU2OTc2NjU3LCJleHAiOjE3NTcwNjMwNTcsImlhdCI6MTc1Njk3NjY1N30.7e69zx98YyEiHR7T0lgOMuZaLnPSPunToFqU9xEoYpA
Accept: application/json



###
GET {{SPT_API_HostAddress}}/spt/c/CourseModel/courses/PET101
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjFkZTJlZDY5IiwibmJmIjoxNzU2OTc2NjU3LCJleHAiOjE3NTcwNjMwNTcsImlhdCI6MTc1Njk3NjY1N30.7e69zx98YyEiHR7T0lgOMuZaLnPSPunToFqU9xEoYpA
Accept: application/json

###
POST {{SPT_API_HostAddress}}/spt/c/CourseModel/addcourse
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjFkZTJlZDY5IiwibmJmIjoxNzU2OTc2NjU3LCJleHAiOjE3NTcwNjMwNTcsImlhdCI6MTc1Njk3NjY1N30.7e69zx98YyEiHR7T0lgOMuZaLnPSPunToFqU9xEoYpA
Content-Type: application/json
{
  "cuuid": "1de2ed69",
  "courseCode": "PET201",
  "courseTitle": "Introduction to Petroleum Engineering II",
  "courseUnit": 3
}
###

DELETE {{SPT_API_HostAddress}}/spt/c/CourseModel/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjFkZTJlZDY5IiwibmJmIjoxNzU2OTc2NjU3LCJleHAiOjE3NTcwNjMwNTcsImlhdCI6MTc1Njk3NjY1N30.7e69zx98YyEiHR7T0lgOMuZaLnPSPunToFqU9xEoYpA
Content-Type: application/json
{
    "_CourseCode": "PET201",
    "CourseDescript": "Introduction to Petroleum Engineering II"
}
###
PATCH {{SPT_API_HostAddress}}/spt/c/CourseModel/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjFkZTJlZDY5IiwibmJmIjoxNzU2OTc2NjU3LCJleHAiOjE3NTcwNjMwNTcsImlhdCI6MTc1Njk3NjY1N30.7e69zx98YyEiHR7T0lgOMuZaLnPSPunToFqU9xEoYpA
Content-Type: application/json
{
    "CourseCode": "PET101",
    "CourseTitle": "Introduction to Petroleum Engineering I",
    "CourseUnit": 3
}