@SPT_API_HostAddress = http://localhost:5119

GET {{SPT_API_HostAddress}}/spt/StudentModel
Accept: application/json

###  
GET {{SPT_API_HostAddress}}/spt/StudentModel/search?FirstName=David&LastName=Oyem
Accept: application/json

###
POST {{SPT_API_HostAddress}}/spt/StudentModel
Content-Type: application/json
{
  "firstName": "David",
  "lastName": "Oyem",
  "department": "Petroleum Engineering",
  "level": "400",
  "studentPassword":"Vision@cu",
}
###
DELETE {{SPT_API_HostAddress}}/spt/StudentModel/delete
Content-Type: application/json
{
  "_firstName": "David",
  "_lastName": "Oyem",
  "_studentUsername": "daoyec",
  "_studentPassword": "Vision@cu"
}
###
PATCH {{SPT_API_HostAddress}}/spt/StudentModel/edit/daoy42
Content-Type: application/json
{
    "email": "oyemdavid12@gmail.com"
}
###
POST {{SPT_API_HostAddress}}/spt/StudentModel/login
Content-Type: application/json
{
    "_Email": "oyemdavid12@gmail.com",
    "_Password": "Vision@cu"
}

###