// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPT_API.Data;

#nullable disable

namespace SPT_API.Migrations
{
    [DbContext(typeof(SPT_APIDbContext))]
    [Migration("20250830202852_AddedCourseTable")]
    partial class AddedCourseTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("SPT_API.Models.CourseModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseTitle")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("CourseUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cuuid")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("cuuid");

                    b.ToTable("CourseTable");
                });

            modelBuilder.Entity("SPT_API.Models.StudentModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("studentPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("studentUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("uniqueUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("uniqueUserId")
                        .IsUnique();

                    b.ToTable("StudentTable");
                });

            modelBuilder.Entity("SPT_API.Models.CourseModel", b =>
                {
                    b.HasOne("SPT_API.Models.StudentModel", "Student")
                        .WithMany("Courses")
                        .HasForeignKey("cuuid")
                        .HasPrincipalKey("uniqueUserId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SPT_API.Models.StudentModel", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
