// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPT_API.Data;

#nullable disable

namespace SPT_API.Migrations
{
    [DbContext(typeof(SPT_APIDbContext))]
    [Migration("20250827134627_UsernameandPasswordAdded")]
    partial class UsernameandPasswordAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("SPT_API.Models.StudentModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("_numLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("studentPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("studentUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("uniqueUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("StudentTable");
                });
#pragma warning restore 612, 618
        }
    }
}
