// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPT_Management_System_Console_App;

#nullable disable

namespace SPT_Management_System_Console_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250813141508_addedstudentlogin")]
    partial class addedstudentlogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("SPT_Management_System_Console_App.Models_Classes.Course_Model", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_CuniqueUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("courseCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("courseUnit")
                        .HasColumnType("INTEGER");

                    b.HasKey("_id");

                    b.HasIndex("_CuniqueUserId");

                    b.ToTable("CourseTable");
                });

            modelBuilder.Entity("SPT_Management_System_Console_App.Student_Model", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("_numLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("studentLogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("uniqueUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("_id");

                    b.HasIndex("uniqueUserId")
                        .IsUnique();

                    b.ToTable("StudentTable");
                });

            modelBuilder.Entity("SPT_Management_System_Console_App.Models_Classes.Course_Model", b =>
                {
                    b.HasOne("SPT_Management_System_Console_App.Student_Model", "Student")
                        .WithMany("studentCourses")
                        .HasForeignKey("_CuniqueUserId")
                        .HasPrincipalKey("uniqueUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SPT_Management_System_Console_App.Student_Model", b =>
                {
                    b.Navigation("studentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
